# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qjh5LiFSXKk8GqkDFlJGUkEMQkfjIOAi
"""

import streamlit as st
import easyocr
import numpy as np
from PIL import Image
import cv2

st.title("Automatic Number Plate Recognition (ANPR) App")

uploaded_file = st.file_uploader("Upload an image of a vehicle", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_column_width=True)

    # Convert image to numpy array for processing
    np_image = np.array(image)
    if np_image.shape[2] == 4:
        np_image = cv2.cvtColor(np_image, cv2.COLOR_RGBA2RGB)
    reader = easyocr.Reader(['en'])  # Use 'en' for English

    with st.spinner('Processing...'):
        # Perform OCR
        results = reader.readtext(np_image)

        st.header("Detected License Plate(s):")
        plates = []
        for (bbox, text, prob) in results:
            # Heuristic: typical number plate length
            if 6 <= len(text) <= 12:
                plates.append((text, prob))

        if plates:
            for plate, confidence in plates:
                st.write(f"**Plate:** {plate} - Confidence: {confidence:.2f}")
        else:
            st.write("No license plate detected.")